# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5200d2e7f0ecb34d7815a0e1cd44e363aaed438ba450cd95cf48ab0be4301473b78365acb95d8891aa6f3cbff784a6466f6b8ef31ec6243bd78600f7534bedce

test:
  secret_key_base: 3b26da6ac26f87d12ba5dc3e0a5a689f4641f6c886ed0b2698683c7211bfbd0285d0090992b490a7bdeb834f1de550ffde455947306cebd736e670b381940b66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
